option(ENABLE_CPPCHECK "Enable static analysis with cppcheck")
option(ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy")
option(CLANG_TIDY_FIX "Perform fixes for Clang-Tidy")

if (ENABLE_CPPCHECK)
    find_program(CPPCHECK cppcheck)
    if (CPPCHECK)
        set(CMAKE_CXX_CPPCHECK ${CPPCHECK} --language=c++ --suppress=missingIncludeSystem --check-config --enable=all --inconclusive)
    else ()
        message(SEND_ERROR "cppcheck requested but executable not found")
    endif ()
endif ()

if (ENABLE_CLANG_TIDY)
    find_program(CLANGTIDY clang-tidy)
    if (CLANGTIDY)
        if (CLANG_TIDY_FIX)
            set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};-header-filter=.;-checks=*,-fuchsia-*,-google-*,-zircon-*,-abseil-*,-modernize-use-trailing-return-type,-llvm-*;" "-fix")
        else ()
            set(CMAKE_CXX_CLANG_TIDY "${CLANGTIDY};-header-filter=.;-checks=*,-fuchsia-*,-google-*,-zircon-*,-abseil-*,-modernize-use-trailing-return-type,-llvm-*;")
        endif ()
    else ()
        message(SEND_ERROR "clang-tidy requested but executable not found")
    endif ()
endif ()
